export const DEFAULT_SERVICES = [
  {
    iconUrl: null,
    id: 'demo-chatgpt',
    name: 'ChatGPT',
    shortDesc: 'Чат-ассистент для текста, кода, идей и анализа.',
    slug: 'chatgpt',
    source: 'demo',
    tags: [
      { name: 'Текст', slug: 'text' },
      { name: 'Код', slug: 'code' },
    ],
    url: 'https://chat.openai.com',
  },
  {
    iconUrl: null,
    id: 'demo-claude',
    name: 'Claude',
    shortDesc: 'Сильный ассистент для текста, документов и программирования.',
    slug: 'claude',
    source: 'demo',
    tags: [
      { name: 'Текст', slug: 'text' },
      { name: 'Код', slug: 'code' },
    ],
    url: 'https://claude.ai',
  },
  {
    iconUrl: null,
    id: 'demo-midjourney',
    name: 'Midjourney',
    shortDesc: 'Генерация изображений по промпту.',
    slug: 'midjourney',
    source: 'demo',
    tags: [{ name: 'Картинки', slug: 'image' }],
    url: 'https://www.midjourney.com',
  },
  {
    iconUrl: null,
    id: 'demo-runway',
    name: 'Runway',
    shortDesc: 'AI-видео: генерация и монтаж.',
    slug: 'runway',
    source: 'demo',
    tags: [{ name: 'Видео', slug: 'video' }],
    url: 'https://runwayml.com',
  },
  {
    iconUrl: null,
    id: 'demo-perplexity',
    name: 'Perplexity',
    shortDesc: 'AI-поиск с источниками, хорош для ресёрча.',
    slug: 'perplexity',
    source: 'demo',
    tags: [{ name: 'Поиск', slug: 'search' }],
    url: 'https://www.perplexity.ai',
  },
  {
    iconUrl: null,
    id: 'demo-n8n',
    name: 'n8n',
    shortDesc: 'Автоматизация процессов: интеграции, боты, пайплайны.',
    slug: 'n8n',
    source: 'demo',
    tags: [{ name: 'Автоматизация', slug: 'automation' }],
    url: 'https://n8n.io',
  },
];
